# Generated by Django 5.0.3 on 2024-04-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ustalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('xizmatlar', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='def.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_fio', models.CharField(max_length=200)),
                ('avtosi', models.CharField(max_length=200)),
                ('rangi', models.CharField(max_length=200)),
                ('diagnostika', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usta_yonalishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.ustalar')),
                ('yonalish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.yonalishlar')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostikalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usta_haqqi', models.CharField(max_length=200)),
                ('servis', models.CharField(max_length=200)),
                ('usta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.ustalar')),
                ('zakaz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.zakaz')),
            ],
        ),
    ]
