# Generated by Django 5.0.3 on 2024-04-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0002_rename_xizmatlar_yonalishlar_hizmatlar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yonalishlar',
            old_name='hizmatlar',
            new_name='xizmatlar',
        ),
    ]
